---
title: "Wavelet Decomposition"
author: "Jeffrey D Walker"
date: "August 15, 2014"
output:
  html_document:
    toc: yes
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Wavelet Decomposition}
-->

## Load Data

```{r load libraries, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
theme_set(theme_bw())
library(weatherGen)
library(forecast)
```

```{r load data}
data(climate)

# compute daily averages across sites
clim.da <- group_by(climate, DATE) %>%
  summarise(N=n(),
            PRCP=mean(PRCP),
            TMIN=mean(TMIN),
            TMAX=mean(TMAX))

# aggregate by water year
clim.wyr <- clim.da %>%
  mutate(WYEAR=ifelse(month(DATE)>=10, year(DATE)+1, year(DATE))) %>%
  group_by(WYEAR) %>%
  summarise(N=n(),
            PRCP=sum(PRCP),
            TMIN=mean(TMIN),
            TMAX=mean(TMAX))
```

```{r plot annual data, fig.cap="Annual Timeseries"}
ggplot(clim.wyr, aes(WYEAR, PRCP)) +
  geom_line() +
  labs(x="Water Year", y="Annual Precipitation (mm)")
```

## Wavelet Decomposition

After performing a wavelet transform, we can use the resulting global power spectrum to reconstruct each frequency component. This was done in Scott's original `WAVE_DECOMPOSITION()` function.

```{r wave decomp}
wave_decomp <- wavelet_decomposition(x=clim.wyr$PRCP, n.periods=1, 
                                     sig.periods=seq(8,15), n.comp.periods=8, 
                                     plot_flag=TRUE)
```

Here is the code used in `WAVELET_DECOMPOSITION()` to construct the frequency components.

```{r}
wavelet_analysis <- wavelet_annual(x=clim.wyr$PRCP, sig=0.90, noise.type="white", 
                                   plot.flag=FALSE)
bw <- biwavelet::wt(d=cbind(1:nrow(clim.wyr), clim.wyr$PRCP), dt=1, dj=1/4, 
                    max.scale=nrow(clim.wyr), sig.level=0.90, lag1=0, sig.test=1)
bw$gws <- apply(bw$power, 1, mean)
bw$gws.sig <- wt.sig(d=clim.wyr$PRCP, dt=bw$dt, scale=bw$scale, sig.test=1, 
                     sig.level=0.90, dof=nrow(clim.wyr)-bw$scale, 
                     mother='morlet', lag1=0.0)

# plot(bw$period, bw$gws)
# lines(bw$period, bw$gws.sig$signif)
signif.periods <- bw$period[which(bw$gws > bw$gws.sig$signif)]

Cdelta <- .776
w0_0 <- pi^(-1/4)

freq.comps <- sd(clim.wyr$PRCP)*(bw$dj*sqrt(bw$dt)/(Cdelta*w0_0))*Re(bw$wave)/sqrt(bw$scale)
colnames(freq.comps) <- seq(1, ncol(freq.comps))
df.freq.comps <- as.data.frame(cbind(freq.comps, scale=bw$scale, period=bw$period)) %>%
  mutate(is.signif = period %in% signif.periods) %>%
  gather(timestep, value, -scale, -period, -is.signif)

df.freq.comps %>%
  mutate(str_scale=format(scale, digits=4),
         str_period=format(period, digits=4),
         timestep=as.numeric(as.character(timestep))) %>%
  arrange(scale, timestep) %>%
ggplot(aes(timestep, value, group=str_period, color=is.signif)) +
  geom_line() +
  facet_wrap(~str_period) +
  scale_color_manual('', 
                     values=c('TRUE'='red', 'FALSE'='black'), 
                     labels=c('TRUE'='Significant', 'FALSE'='Not Significant')) +
  theme(legend.position='bottom')

df.freq.comps.signif <- filter(df.freq.comps, is.signif) %>%
  select(period, timestep, value) %>%
  mutate(period=paste0('Period-', format(period, digits=3))) %>%
  spread(period, value)
df.freq.comps.signif$Period_Sum <- select(df.freq.comps.signif, -timestep) %>%
  rowSums()
df.freq.comps.signif$Noise <- clim.wyr$PRCP - df.freq.comps.signif$Period_Sum
df.freq.comps.signif$Sum <- df.freq.comps.signif$Period_Sum + df.freq.comps.signif$Noise
df.freq.comps.signif$Precip <- clim.wyr$PRCP

gather(df.freq.comps.signif, Component, Value, -timestep, -Sum, -Period_Sum) %>%
  ggplot(aes(timestep, Value, group=Component)) +
  geom_line() +
  facet_wrap(~Component, ncol=1)
```

# Appendix

```{r session}
sessionInfo()
```

