#' Run Markov Chain Simulation
#'
#' @param months numeric array of months for each daily time step
#' @param initial initial state
#' @param states character vector of markov states
#' @param transitions monthly list of transition matrices generated by fit_mc()
#' @export
#' @examples
#' transitions <- fit_mc(x=sample(c('d', 'w', 'e'), size=720, replace=TRUE, prob=c(0.5, 0.3, 0.2)), months=rep(rep(seq(1, 12), each=30), times=2))
#' sim_mc(months=rep(1:12, each=30), initial='d', states=c('d', 'w', 'e'), transitions=transitions)
#'
sim_mc <- function(months, initial, states, transitions) {
  n <- length(months)

  chain <- rep(NA_character_, times=n)
  chain[1] <- initial

  for (i in 2:n) {
    chain[i] <- sample(states, size=1, prob=transitions[[months[i-1]]][chain[i-1], ])
  }

  chain <- ordered(chain, levels=states)

  chain
}

#' Fit Markov Chain Transition Matrices to Observed States
#'
#' @param x character array of states as ordered factor
#' @param months numeric array of months for each daily time step
#' @export
#' @examples
#' transitions <- fit_mc(x=sample(c('d', 'w', 'e'), size=720, replace=TRUE, prob=c(0.5, 0.3, 0.2)), months=rep(rep(seq(1, 12), each=30), times=2))
#'
fit_mc <- function(x, months) {
  stopifnot(length(x) == length(months))
  x_next <- lead(x)
  transitions <- lapply(seq(1, 12), function(m) {
    idx <- which(months==m)
    prop.table(table(x[idx], x_next[idx]), 1)
  })
  transitions
}