#' Wavelet analysis of annual timeseries
#'
#' @param x annual values of climate timeseries (e.g. precipitation) as numeric array
#' @param sig.level significance level
#' @param noise.type type of background noise ("white" or "red")
#' @export
#' @examples
#' wavelet_analysis(x=runif(30)*100+200, sig=0.90, noise.type="white", plot.flag=TRUE)
#'
wavelet_analysis <- function(x, sig.level=0.90, noise.type=c("white", "red")) {
  noise.type <- match.arg(noise.type)
  lag1 <- switch(noise.type,
                 white = 0,
                 red = 0.72)

  bw <- biwavelet::wt(d=cbind(1:length(x), x), dt=1, dj=1/4, max.scale=length(x),
                      lag1=lag1, sig.level=sig.level, sig.test=0)

  # time-averaged global wave spectrum
  bw$gws <- apply(bw$power, 1, mean)
  bw$gws.sig <- biwavelet::wt.sig(d=x, dt=bw$dt, scale=bw$scale, sig.test=1,
                                  sig.level=sig.level, dof=length(x)-bw$scale,
                                  mother='morlet', lag1=lag1)

  return(bw)
}

#' Reconstruct wavelet components
#'
#' @param x annual timeseries of observed climate variable as numeric vector
#' @param wt wavelet transform generated by wavelet_analysis()
#' @param n.periods number of final composite periods
#' @param sig.periods integer array of significance periods
#' @param n.comp.periods number of significance periods for each composite period
#' @param plot_flag boolean flag to show plots
#' @export
#' @examples
#' wavelet_components(x=x, n.periods=1, sig.periods=seq(8,15), n.comp.periods=8)
wavelet_components <- function(x, wt, n.periods, sig.periods, n.comp.periods) {
  freq.comps <- array(0,c(length(x),n.periods))
  for (i in 1:n.periods) {
    cur.periods <- sig.periods[1:n.comp.periods[i]]
    if (i>1) {
      cur.periods <- sig.periods[(1 + (i-1)*n.comp.periods[i-1]):(n.comp.periods[i] + (i-1)*n.comp.periods[i-1])]
    }
    sj <- wt$scale[cur.periods]
    #for Morlet Wavelet with freq = 6
    Cdelta <- .776
    w0_0 <- pi^(-1/4)
    components <- (wt$dj*sqrt(wt$dt)/(Cdelta*w0_0))*Re(wt$wave)[cur.periods,]/sqrt(sj)
    if (length(cur.periods)>1) {
      components <- apply(components, 2, sum)
    }
    freq.comps[,i] <- components
  }

  noise <- x - apply(freq.comps, 1, sum)

  colnames(freq.comps) <- paste("COMPONENT", 1:n.periods, sep=' ')

  return(cbind(NOISE=noise, freq.comps))
}



